### ISSUE TITLE
Problem with directives when used in combination with Vuetify

### ISSUE THREAD

**Issue by WieFel** [Meqn/v-resize-observer#2]
In my project I use `v-resize-observer` in combination with [Vuetify](https://vuetifyjs.com/en/) which exposes a directive [v-resize](https://vuetifyjs.com/en/directives/resize/).

As the Vuetify property is named exactly the same as the directive `v-resize` exposed by `v-resize-observer`, I am not able to correctly use the directive of `v-resize-observer`.

@Meqn I suppose that the directive would have to be renamed to be compatible with Vuetify!?
Is there a way I can do that locally, e.g. when importing the `v-resize-observer` package?

CC: @MikeYakovlev

**Comment by Meqn** [comment]
@WieFel 
Sorry, I have been busy with work recently and have not paid attention to this project for the time being。

For this problem, you can only import directive

```js
import resizeDirective from 'v-resize-observer/src/directive'

export default {
  directives: {
    resizeObserver: resizeDirective
  }
}
```

**Comment by Marinerer** [comment]
@WieFel 

```vue
<template>
  <div v-resize-observer:debounce="handleResize">
    content
  </div>
</template>
<script>
import ResizeObserver from 'v-resize-observer'

export default {
  directives: {
    resizeObserver: ResizeObserver.directive
  },
  methods: {
    handleResize({ width, height }, target) {
      console.log(`width: ${width}, height: ${height}`)
    }
  }
}
</script>
```
