### ISSUE TITLE
能否加入参数使其立即执行？

### ISSUE THREAD

**Issue by xueke-alan** [Meqn/v-resize-observer#7]
有的时候需要立即执行一次以获取宽高属性并进行处理。需要额外获取对象找到宽度，在执行一次onresize函数，希望可以加入一个参数immediate，类似于watch中的immediate，这样可以少写许多代码。

**Comment by Marinerer** [comment]
@xueke-alan 
好的，我空了评估下。

**Comment by Marinerer** [comment]
@xueke-alan 
已更新
https://github.com/Meqn/v-resize-observer/releases/tag/v2.1.0
